language: python
sudo: required
python:
  - "2.7"
services:
  - redis-server
  - mongodb
install:
  - "pip install --upgrade -r requirements/requirements.txt"
  - "pip install --upgrade -r requirements/testing.txt"
  - "pip install --upgrade -r requirements/development.txt"
script: make test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - lingo4barter@gmail.com